---
title: "Homework #5"
author: "Sophia Miller"
date: "11/3/2019"
output: github_document
---
```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(broom)
set.seed(1)
```

# Problem 1

First, we will load the `iris` dataset and introduce missing values in each column: 

```{r iris}
set.seed(10)
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

The function below replaces missing values according to the following rules:

* For numeric variables, missing values are filled in with the mean of non-missing values
* For character values, missing values are filled in with `"virginica"`

```{r replace_missing_function}
replace_missing = function(x) {
  
   if (is.numeric(x)) {
    ifelse(is.na(x), mean(x, na.rm = TRUE), x)
   } else if (is.character(x)) {
     ifelse(is.na(x), "virginica", x)
   }
     
}

iris_complete = map_df(iris_with_missing, replace_missing)
```

# Problem 3

```{r regression}
sim_regression = function(n = 30, beta0 = 2, beta1 = 0) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 50),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)

  tidy(ls_fit)

}

output = vector("list", 1000)

for (i in 1:1000) {
  output[[i]] = sim_regression()
}

sim_results = bind_rows(output)
```


